name: example
description: Example of Bubble widget

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #bubble: ^1.1.10
  bubble:
    path: ../

  flutter:
    sdk: flutter

  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
